!!dk.dma.epd.ship.settings.layers.OwnShipLayerSettings {movementVectorHideBelow: 0.1,
  movementVectorLengthMax: 8, movementVectorLengthMin: 1, movementVectorLengthStepSize: 5000.0,
  multiSourcePntVisible: false, showVesselNameLabels: false, visible: true}
